### ISSUE TITLE
Any I2C component class not working with esp8266

### ISSUE THREAD

**Issue by d1runberg** [mwittig/etherport-client#2]
Hi,

This works great with the esp8266 using FimataWifi. I have multiple boards report to a single Tessel 2 as well as it working on my laptop. My issue is when i try to add an i2c sensor to my project (specifying the board.byId ()) nothing happens. The event listener never fires on change or data. There is no error kicked.

I have tried this with the BME280 as well as an i2c accelerometer.

Tried with a single esp8266 controlled by my laptop with the same results.

**Comment by mwittig** [comment]
Would you mind sharing your code with me? This would help me to better understand and reproduce the problem. I don't have the BME280 at hand, but I have several other I2C sensor I could use for my own test setup.

**Comment by d1runberg** [comment]
Yeah! Sorry, I posted it from my phone away from my code. Here is what I am trying to run.

```
const five = require('johnny-five');
const EtherPortClient = require('etherport-client').EtherPortClient;

const esp = new five.Board({
    port: new EtherPortClient({
            host: '10.0.0.193', // IP address of the ESP
            port: 3030
        }),
    timeout: 1e5,
    repl: true});

esp.on('ready', ()=>{
  console.log('esp connected!');
  const accel = new five.Accelerometer({
    controller: "ADXL345"
  });

  accel.on('change', ()=>{
    console.log(accel.orientation);
  });
});
```

I get the "esp connected" log, but then nothing after that.

**Comment by d1runberg** [comment]
I know that is may well be a Firmata problem and not an etherport-client problem.

**Comment by mwittig** [comment]
Most likely it is a problem elesewhere as EtherPortClient does simple message passing no matter what the data is

**Comment by mwittig** [comment]
@d1runberg Did you manage to get it working?

**Comment by d1runberg** [comment]
I never did, but havent tried in a while. I will try again this week.

**Comment by mwittig** [comment]
Assuming this has been solved until further feedback

**Comment by techlinxweb** [comment]
I'm trying the same problem, firm on esp8266 and an arduino mini pro via i2c with a DHT22

**Comment by rodrigoadachi** [comment]
I'm trying the same problem, firm on esp8266 and an arduino mini pro via i2c with a DHT22

**Comment by mwittig** [comment]
Guys,I don't think this is an issue with EtherportClient, but it might be an issue with FirmataWifi. See here:

https://github.com/firmata/arduino/issues/304
